server:
  port: 8080
spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${budget.datasource.driver-class-name}
      url: jdbc:mysql://${budget.datasource.host}:${budget.datasource.port}/${budget.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${budget.datasource.username}
      password: ${budget.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.budget.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      budget:
        mapper: debug
        service: info
        controller: info

budget:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: jiejie
    # 设置jwt过期时间
    ttl: 72000000000
    # 设置前端传递过来的令牌名称
    token-name: token
